### ISSUE TITLE
App crashes in background mode

### ISSUE THREAD

**Issue by idanixno** [blueboy-tm/flutter_v2ray#1]
Hello, don't worry about the plugin you used for Flutter, you are right
When I connect to vpn with this package, everything is fine, but when I close the app in debug mode and open it again, it crashes as soon as it comes up.

**Comment by idanixno** [comment]
https://github.com/blueboy-tm/flutter_v2ray/assets/130180635/c89979fb-b947-4f39-b14f-cd97b82f564b

**Comment by blueboy-tm** [comment]
> Hello, don't worry about the plugin you used for Flutter, you are right When I connect to vpn with this package, everything is fine, but when I close the app in debug mode and open it again, it crashes as soon as it comes up.

Hi there
I need to check the program log for your problem

**Comment by blueboy-tm** [comment]
https://github.com/blueboy-tm/flutter_v2ray/assets/49907537/a2ebddc7-b43c-4687-af39-7c2d9df9e0df

**Comment by blueboy-tm** [comment]
The bug was fixed in the new version

**Comment by idanixno** [comment]
Bang Bang
AzizSan Yourolma
