### ISSUE TITLE
Clarifications in the README

### ISSUE THREAD

**Issue by vanyasem** [blueboy-tm/flutter_v2ray#12]
It'd be great if you added the currently used version of V2Ray/Xray to the README
And when updating it, mention the new version of V2Ray/Xray in the changelog

Also it's not clear whether it's based on v2ray or xray-core, I feel that this also needs clarification in the README

It'd be great to also document the way the `.aar` library was built (link to a repo with a build script and instructions), or to link the binary `.aar` file if the `.aar` was precompiled by someone else

**Comment by blueboy-tm** [comment]
The currently used version is Xray v24 v1.8.1.4
The readme has been updated
