### ISSUE TITLE
Issue with wifi on YouTube 

### ISSUE THREAD

**Issue by Omidbabadi** [blueboy-tm/flutter_v2ray#15]
Hey, i found out when ever i use wifi to connect to the vpn videos will not play on YouTube
It's load's all the thumbnails but the videos will not be played

Is everyone else facing this issue?

**Comment by blueboy-tm** [comment]
I think the problem might be with your V2Ray server

**Comment by Omidbabadi** [comment]
> I think the problem might be with your V2Ray server
    Yeah you're right i try more configs from different servers and some of them worked and some didn't 
But i wonder why their been ok with v2rayng

**Comment by blueboy-tm** [comment]
Run the program with json output of V2RayNG and check result

**Comment by Omidbabadi** [comment]
I tried with cloudflare warp enabled for YouTube and it's working now.
But still confused why it doesn't have any problems on other clients


Anyway thanks for your effort on this ❤️
