### ISSUE TITLE
Crashs & ANR  After upload google play

### ISSUE THREAD

**Issue by abbasnazari-0** [blueboy-tm/flutter_v2ray#16]
Hello everyone
after I published my app to Google Play, my app opened successfully but the VPN tunnel did not start
and I check the uploaded app with ADB  logs, but I can't find an exact response

after I reviewed it for a long time, I found an error in the Google Play console, I found these error

1- 
![image](https://github.com/blueboy-tm/flutter_v2ray/assets/49541849/08b68a9a-6773-497a-b194-8a1d40521f71)
![image](https://github.com/blueboy-tm/flutter_v2ray/assets/49541849/5163ee7a-0af5-4330-b0dc-d46c143c5a95)

I think I had these errors for getting a delay error

---
2-
![image](https://github.com/blueboy-tm/flutter_v2ray/assets/49541849/1f10211d-9314-4ff2-bd7a-ddfc81fbc5cb)
![image](https://github.com/blueboy-tm/flutter_v2ray/assets/49541849/010a04bf-fff6-4439-933b-b6bcace37ef1)
and this error occurred in connecting tunnel traffic

**Comment by blueboy-tm** [comment]
https://github.com/blueboy-tm/flutter_v2ray#android-configuration-befor-publish-to-google-play
