### ISSUE TITLE
app has crashed when is closed and reopen

### ISSUE THREAD

**Issue by amir-noroozi** [blueboy-tm/flutter_v2ray#2]
https://github.com/blueboy-tm/flutter_v2ray/assets/45897142/0d4dff40-f2e8-4e04-bb8a-367de3bd827b

**Comment by blueboy-tm** [comment]
> 2.mp4

check this issue https://github.com/blueboy-tm/flutter_v2ray/issues/1

**Comment by blueboy-tm** [comment]
> 2.mp4


The bug was fixed in the new version
