### ISSUE TITLE
close app after update 1.0.5

### ISSUE THREAD

**Issue by pesaregorg** [blueboy-tm/flutter_v2ray#24]
I updated the package to version 1.0.5. This version causes the application to force close and disconnect the VPN connection.

**Comment by Omidbabadi** [comment]
I had the same experience

**Comment by abbasnazari-0** [comment]
I had the same experience

**Comment by AbsamatDev** [comment]
same

**Comment by einkaaf** [comment]
Would it be recommended to execute the `connect `method within a background Service? I'm curious about its compatibility and potential impact in that context.

**Comment by pesaregorg** [comment]
@einkaaf 
This package works well in the background. Even if the application is closed by the user.

**Comment by einkaaf** [comment]
> @einkaaf 
> This package works well in the background. Even if the application is closed by the user.

Yes but the version 1.0.4

**Comment by hashemim66110** [comment]
it was okay till like yesterday.
suddenly problem appears and stay.

please delete 1.0.5 release if you could so we can use older version that work, until 1.0.6 come out and solve problem.

**Comment by einkaaf** [comment]
> it was okay till like yesterday. suddenly problem appears and stay.
> 
> there is no problem with android 6 btw. only newer androids disconnect.

the solution is you migrate to last version 1.0.4
Be careful of the cache of package in flutter !
