### ISSUE TITLE
crash app Flutter 3.16

### ISSUE THREAD

**Issue by idanixno** [blueboy-tm/flutter_v2ray#25]
When I updated Flutter to version 3.16, this bug appeared in my project. I even created a new test project, and I saw a crash error again. Where does the problem come from?

![image](https://github.com/blueboy-tm/flutter_v2ray/assets/130180635/54eb877e-274a-4aa8-8afb-da28627b14f9)

**Comment by zikwall** [comment]
same error, how did you manage to fix it?
