### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by Omidbabadi** [blueboy-tm/flutter_v2ray#27]
I tested it on Android 14 and having some problems there.

The vpn connection will stablish but
 value.state == "DISCONNECT" will remain true .
I'm using other packages on project too
So I'm not sure if flutter_v2ray is making problem or one of those.

I will test more to make sure.

**Comment by blueboy-tm** [comment]
Your condition should be like this
value.state == "DISCONNECTED"

**Comment by Omidbabadi** [comment]
> Your condition should be like this
> value.state == "DISCONNECTED"
> 

Yeah i write value.state == "DISCONNECTED" on my code
I just forget it when writing the issue here

Also I'm using 1.03 version I'll try with latest
