### ISSUE TITLE
Problem with GeoIP

### ISSUE THREAD

**Issue by zikwall** [blueboy-tm/flutter_v2ray#29]
I get an error

```
E/getV2rayServerDelayCore( 8278): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: private > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open /system/bin/geoip.dat: no such file or directory
```

version: 1.0.4
Flutter 3.16.0 • channel stable • git@github.com:flutter/flutter.git
Framework • revision db7ef5bf9f (4 weeks ago) • 2023-11-15 11:25:44 -0800
Engine • revision 74d16627b9
Tools • Dart 3.2.0 • DevTools 2.28.2

**Comment by blueboy-tm** [comment]
An error has occurred related to not finding the geoip database at the path /system/bin/geoip.dat. This file is associated with your Android device. Please check if the file exists and is intact.

**Comment by pishguy** [comment]
@blueboy-tm  How can we use GeoIP database files alongside our program by incorporating them?
