### ISSUE TITLE
not working with reality

### ISSUE THREAD

**Issue by abbasnazari-0** [blueboy-tm/flutter_v2ray#3]
Hi there 
i think it not working with reality config
please recheck with relality

thanks

**Comment by blueboy-tm** [comment]
> Hi there i think it not working with reality config please recheck with relality
> 
> thanks

The plugin uses xray 1.8.1 and has the ability to connect to reality
I compared the configuration made by vrayNG and flutter_v2ray and both of them have the same output.
According to these things it should work properly

**Comment by abbasnazari-0** [comment]
so when i connecto to reality 
it print this error : E/getV2rayServerDelay( 6623): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: VLESS users: "flow" doesn't support "xtls-rprx-vision" in this version
