### ISSUE TITLE
what is Large Size of package for ?

### ISSUE THREAD

**Issue by hashemim66110** [blueboy-tm/flutter_v2ray#32]
flutter sample project apk build by default needs 5.4mb space compressed and about 11mb after install.
but when we add this package to project it takes up to 57mb of size Conpressed!
what is this large size for ?

**Comment by blueboy-tm** [comment]
The reason for the large size of the tun2socks package is that it is separated for each architecture. When you build the program, Flutter collects all of them into a single APK, which works on all phones. The solution is to have a separate APK for each architecture, reducing the size significantly. You can achieve this with the command: `flutter build apk --split-per-abi`.
