### ISSUE TITLE
Customize Notifications

### ISSUE THREAD

**Issue by mohammadzamani-dev** [blueboy-tm/flutter_v2ray#37]
Hey blueboy, thank you for your good supports on this package.🫶
there is a minor problem with this package. i want to add custom notification when v2ray connects but there is no customizable options with it. so i decided to disable the notification thrown from this package and create my custom notification, but again there is no option to disable it. and when i forked the repository to delete the notification parts of package, the package works but after 45 seconds from starting connection, it throws Stopped Working error on phone. please find a great solution for this issue. i really appreciate it.
thanks again.

**Comment by smj1234** [comment]
you can customize it by send it in same channel  , At least it works for me !

**Comment by mohammadzamani-dev** [comment]
> you can customize it by send it in same channel , At least it works for me !

I tried to create a new notification with the same channel, but still two notifications were shown. Is this the notification channel of this package or did I misunderstand?
DEV7_DEV_V_E_CH_ID
i appreciate if you provide me your solution

**Comment by smj1234** [comment]
> > you can customize it by send it in same channel , At least it works for me !
> 
> I tried to create a new notification with the same channel, but still two notifications were shown. Is this the notification channel of this package or did I misunderstand? DEV7_DEV_V_E_CH_ID i appreciate if you provide me your solution


Hi can you provide with picture You mean that you can see 2 different notifications or jus+1 on the top of your notification ? cause it working background it provide the running inform so you cannot get rid of that "+1" on the title of notification unless you change the whore package or re assign the ids.
 are you using notification packages or just using flutter native solutions ? you can try using some packages like awesome and first cancel all then send yours

**Comment by RaminBgrn** [comment]
hi
have you found a solution for customize notification ?

**Comment by mohammadzamani-dev** [comment]
> hi
> have you found a solution for customize notification ?

Hi Ramin. I fully deleted the codes where were related to notifications from package and created my custom notification in my flutter code. Everything working nicely.

**Comment by pishguy** [comment]
@mohammadzamani-dev could you share your implemented notification in flutter please? could you open application when v2ray is connected and app is in foreground?

**Comment by RaminBgrn** [comment]
> > hi
> > have you found a solution for customize notification ?
> 
> Hi Ramin. I fully deleted the codes where were related to notifications from package and created my custom notification in my flutter code. Everything working nicely.

thanks for your response
So you rewrote the Java side right?

**Comment by AliNajafzadeh7916** [comment]
> > سلام 
> > آیا راه حلی برای سفارشی سازی اعلان پیدا کرده اید؟
> 
> سلام رامین. کدهایی که مربوط به اعلان‌ها بود را به طور کامل از بسته حذف کردم و اعلان سفارشی خود را در کد فلوتر خود ایجاد کردم. همه چیز به خوبی کار می کند

درود وقت بخیر کد ها رو کامنت کردم ولی بازم بعد 40 تا 50 ثانیه ران بودن نات رسپاندینگ میده

**Comment by blueboy-tm** [comment]
I added a disconnect button in the last commit
