### ISSUE TITLE
نیازمند  همین پروژه

### ISSUE THREAD

**Issue by ahwazi12** [blueboy-tm/flutter_v2ray#38]
سلام خوبی   این   نرم افزار  رو می خوام  با  همراه  پنل مدیریت  و  ورود کاربر با یوز پس   با چند امکانت دیگه  اگه میشه  درارتباط باشیم

**Comment by blueboy-tm** [comment]
> سلام خوبی   این   نرم افزار  رو می خوام  با  همراه  پنل مدیریت  و  ورود کاربر با یوز پس   با چند امکانت دیگه  اگه میشه  درارتباط باشیم  

سلام توی تلگرام بهم پیام بدید
T.me/blueboy_tm
