### ISSUE TITLE
Written as per the example, the node works, connects but does not access the internet.

### ISSUE THREAD

**Issue by JieNengi** [blueboy-tm/flutter_v2ray#39]
class V2RayManager {
  final FlutterV2ray flutterV2ray =
      FlutterV2ray(onStatusChanged: (V2RayStatus status) {});

  Future<void> initializeV2Ray() async {
    await flutterV2ray.initializeV2Ray();
  }

  V2RayURL parseLink({required String link}) {
    return FlutterV2ray.parseFromURL(link);
  }

  Future<void> startV2Ray({required String link}) async {
    if (await flutterV2ray.requestPermission()) {
      final parser = parseLink(link: link);
      flutterV2ray.startV2Ray(
        remark: parser.remark,
        config: parser.getFullConfiguration(),
        blockedApps: null,
        bypassSubnets: null,
        proxyOnly: false,
      );
      if (kDebugMode) {
        Printer.info('地址 ${parser.address}');
        Printer.info('节点 ${parser.remark}');
        Printer.info('dns ${parser.dns}');
      }
    }
  }

  void stopV2Ray() {
    flutterV2ray.stopV2Ray();
  }
}

![image](https://github.com/blueboy-tm/flutter_v2ray/assets/42732005/ccc53fc1-5c9e-4985-8088-52bc00094b5a)

**Comment by smj1234** [comment]
south.eeeeef998.buzz is that the link you gave to parser ?  if the answer is yes maybe you need to try sending full conf link to parser then get the configuration from the .getFullConfiguration() and send it to start()
