### ISSUE TITLE
Not working with tcp transport and http headerType

### ISSUE THREAD

**Issue by H3mnz** [blueboy-tm/flutter_v2ray#4]
Hi

when using the config with tcp transport and http headerType not working
please recheck

**Comment by blueboy-tm** [comment]
Hi there,
Can you give me an example of the config?

**Comment by blueboy-tm** [comment]
> Hi
> 
> when using the config with tcp transport and http headerType not working please recheck

Hi there,
Can you give me an example of the config?

**Comment by H3mnz** [comment]
> > Hi
> > when using the config with tcp transport and http headerType not working please recheck
> 
> Hi there, Can you give me an example of the config?

like this

vless://417a0afa-0141-4fbd-f757-9f29939f4b18@vps1.royalserver.top:443?security=none&encryption=none&host=telewebion.com&headerType=http&type=tcp#vps1-v2rayflutter

**Comment by pishguy** [comment]
@H3mnz could you please explain me whats and how is it work this connection?

```
vless://[417a0afa-0141-4fbd-f757-9f29939f4b18@vps1.royalserver.top](mailto:417a0afa-0141-4fbd-f757-9f29939f4b18@vps1.royalserver.top):443?security=none&encryption=none&host=telewebion.com&headerType=http&type=tcp#vps1-v2rayflutter
```
