### ISSUE TITLE
Problem opening YouTube

### ISSUE THREAD

**Issue by pesaregorg** [blueboy-tm/flutter_v2ray#43]
I can connect to YouTube with a fixed config in napsternetv, but I am not able to connect to YouTube in an application that uses this package. Of course, this happens only with Irancell Internet.

**Comment by Omidbabadi** [comment]
I have the same problem
With irancell only

**Comment by AmanjAmjadi** [comment]
I have the same problem

**Comment by blueboy-tm** [comment]
The issue was with the DNS and has been fixed
