### ISSUE TITLE
is working??? i set config but not work

### ISSUE THREAD

**Issue by farhadadarbar** [blueboy-tm/flutter_v2ray#5]
/AudioManager(31553): querySoundEffectsEnabled...
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): parseV2rayJsonFile failed =>
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): org.json.JSONException: Value vless of type java.lang.String cannot be converted to JSONObject
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at org.json.JSON.typeMismatch(JSON.java:112)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at org.json.JSONObject.<init>(JSONObject.java:163)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at org.json.JSONObject.<init>(JSONObject.java:176)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities.parseV2rayJsonFile(Utilities.java:83)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at com.github.blueboytm.flutter_v2ray.v2ray.V2rayController.StartV2ray(V2rayController.java:43)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at com.github.blueboytm.flutter_v2ray.FlutterV2rayPlugin.lambda$onAttachedToEngine$0$com-github-blueboytm-flutter_v2ray-FlutterV2rayPlugin(FlutterV2rayPlugin.java:57)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at com.github.blueboytm.flutter_v2ray.FlutterV2rayPlugin$$ExternalSyntheticLambda0.onMethodCall(Unknown Source:4)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at android.os.Handler.handleCallback(Handler.java:907)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at android.os.Looper.loop(Looper.java:216)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at java.lang.reflect.Method.invoke(Native Method)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/com.github.blueboytm.flutter_v2ray.v2ray.utils.Utilities(31553): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by blueboy-tm** [comment]
The config you entered is not in the correct format
