### ISSUE TITLE
register Receiver error 

### ISSUE THREAD

**Issue by H3mnz** [blueboy-tm/flutter_v2ray#50]
on target sdk 34 this error happened

One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

changed this line

`context.registerReceiver(receiver, new IntentFilter("V2RAY_CONNECTION_INFO"), null, null)`

to this

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
             context.registerReceiver(receiver, new IntentFilter("V2RAY_CONNECTION_INFO"), Context.RECEIVER_EXPORTED);
        }else {
             context.registerReceiver(receiver, new IntentFilter("V2RAY_CONNECTION_INFO"));
        }
```
and this line

`activity.registerReceiver(v2rayBroadCastReceiver, new IntentFilter("V2RAY_CONNECTION_INFO"))`

to this

```
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
             activity.registerReceiver(v2rayBroadCastReceiver, new IntentFilter("V2RAY_CONNECTION_INFO"), Context.RECEIVER_EXPORTED);
        }else {
             activity.registerReceiver(v2rayBroadCastReceiver, new IntentFilter("V2RAY_CONNECTION_INFO"));
        }
```

please fixed as new version

**Comment by blueboy-tm** [comment]
Hello, please send a pull request

**Comment by mobinaa6** [comment]
Where is this line that should be changed?

**Comment by hashemim66110** [comment]
where should we change this line ?
how to fix it ?

**Comment by hashemim66110** [comment]
those two lines should be changed in :
flutter_v2ray-1.0.7/android/src/main/java/com/github/blueboytm/flutter_v2ray/v2ray/V2rayController.java
and
flutter_v2ray-1.0.7/android/src/main/java/com/github/blueboytm/flutter_v2ray/FlutterV2rayPlugin.java
