### ISSUE TITLE
When is iOS expected to be released?

### ISSUE THREAD

**Issue by liangxiaobo** [blueboy-tm/flutter_v2ray#54]
Hello, when is iOS expected to be released?

**Comment by OnePiece110** [comment]
https://t.me/JohnGG123 I did it

**Comment by loveCodingStar** [comment]
https://t.me/TTMike12
contact me

**Comment by launchpool1** [comment]
tell me your telegram

**Comment by launchpool1** [comment]
Skype: live:.cid.8348de65da727437

**Comment by hasanbayazid** [comment]
> tell me your telegram

Can you help me?

**Comment by maxfu92** [comment]
> tell me your telegram

max_fu_19
Really need your help

**Comment by blueboy-tm** [comment]
The iOS version is completed and available for sale.
