### ISSUE TITLE
proxy only not work

### ISSUE THREAD

**Issue by o10301** [blueboy-tm/flutter_v2ray#6]
Connected but speed is zero. 
![WechatIMG67](https://github.com/blueboy-tm/flutter_v2ray/assets/58681154/483b4ef6-2a1c-41e4-b448-0b16ec2c2e86)

**Comment by blueboy-tm** [comment]
In this case, a socks proxy is created
And when you use a proxy, this traffic will change

**Comment by o10301** [comment]
Not traffic, speed is zero and cannot open google

**Comment by emirmg** [comment]
Same here. Proxy mode not working
