### ISSUE TITLE
Update XrayCore to the latest versions

### ISSUE THREAD

**Issue by AliNajafzadeh7916** [blueboy-tm/flutter_v2ray#70]
The current version of **Xray-Core** is **1.8.7**

Is an update in this case and kernel update also considered?

Because the latest core version is **Xray-Core 1.8.23**

_v2rayng_ uses version **Xray-Core 1.8.16** in its latest update

Thank you for developing and maintaining this package, we will support you financially with your good and more complete updates

🙏❤️

**Comment by amir-zr** [comment]
@AliNajafzadeh7916 use https://pub.dev/packages/flutter_v2ray_client
