### ISSUE TITLE
No Internet Connectivity on targetSdkVersion 34

### ISSUE THREAD

**Issue by shaif-dihan** [blueboy-tm/flutter_v2ray#72]
If the targetSdkVersion is set to 34, the VPN is connected but there is no Internet Connectivity

It is all okay on targetSdkVersion 33

**Comment by tand90** [comment]
I have the same issue, but with minSdkVersion.

If I do not change minSdk and use default flutter.minSdkVersion param (it is 21 for flutter 3.24),  VPN is connected and works great.

But if I change the version of minSdk to 22, 23, 24, etc, VPN connected, but there is no internet connection.
