### ISSUE TITLE
Problem while pinging

### ISSUE THREAD

**Issue by abbasnazari-0** [blueboy-tm/flutter_v2ray#8]
### The program will get stuck and if it ping has -1 , it will take a long time and the program may crash.

      
      I/oper.(10030): Wrote stack traces to '[tombstoned]'
      E/getV2rayServerDelay(10030): go.Universe$proxyerror: Get "http://www.google.com/generate_204": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
      I/GoLog   (10030): Not Using Prepared: tcp,45.12.30.3:80
      E/getV2rayServerDelayCore(10030): go.Universe$proxyerror: Get "http://www.google.com/generate_204": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

![image](https://github.com/blueboy-tm/flutter_v2ray/assets/49541849/3564c637-bd93-4e28-ac7e-f3fb3209c147)

**Comment by abbasnazari-0** [comment]
I tried to isolate it in different threads but it collision to  crush

**Comment by blueboy-tm** [comment]
You cannot get a delay while connecting to a VPN
