### ISSUE TITLE
reality with "xtls-rprx-vision" flow 

### ISSUE THREAD

**Issue by abbasnazari-0** [blueboy-tm/flutter_v2ray#9]
E/getV2rayServerDelayCore(10666): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: VLESS users: "flow" doesn't support "xtls-rprx-vision" in this version

not working with reality with "xtls-rprx-vision" flow 
please recheck it

thank you

**Comment by blueboy-tm** [comment]
The problem was fixed in the last commit
